Repository gpbl/react-day-picker, pull requests merged in 2018-08, with the labels that each got.

#774 Add onClose event handler for DayPickerInput overlay
  package.json
  src/DayPickerInput.js
  test/daypickerinput/events.js
  types/props.d.ts
  yarn.lock
Labels: new feature, src:DayPickerInput, v:minor

#775 Add undefined and null as allowed modifier types
  types/common.d.ts
Labels: src:TypeScript, v:patch

#760 Fix TypeScript type for DayPicker.dayPicker
  types/DayPicker.d.ts
Labels: src:DayPickerInput, src:TypeScript, v:minor

#762 Add top-level type definition for DayPickerInput
  DayPickerInput.d.ts
Labels: src:DayPickerInput, src:TypeScript, v:patch

#777 Change formatting to local em-sizes
  src/style.css
Labels: v:patch

#778 Store the typed value even if an invalid date
  src/DayPickerInput.js
  test/daypickerinput/events.js
Labels: v:patch

#782 Pass dayPickerInput instance to onDayChange
  docs/src/code-samples/examples/input-state.js
  docs/src/pages/api/DayPickerInput.js
  src/DayPickerInput.js
  test/daypickerinput/events.js
  types/props.d.ts
Labels: docs: required update, v:patch

#784 Add DayPickerInput.d.ts to npm bundle
  package.json
Labels: src:TypeScript, v:patch
