Repository gpbl/react-day-picker, pull requests merged in 2019-10, with the labels that each got.

#939 Fix DayPickerInput value does not recompute on locale change
  src/DayPickerInput.js
  test/daypickerinput/rendering.js
Labels: bug:minor, src:DayPickerInput

#929 Improve typings, use TypeScript 3.1
  package.json
  types/DayPicker.d.ts
  types/DayPickerInput.d.ts
  types/README.md
  types/common.d.ts
  types/index.d.ts
  types/moment.d.ts
  types/props.d.ts
  types/tsconfig.json
  types/utils.d.ts
  yarn.lock
Labels: src:TypeScript, v:minor

#923 Make `format` optional in DayPickerInput
  types/props.d.ts
Labels: src:DayPickerInput, src:TypeScript

#873 Add formatDate and parseDate to typings
  types/utils.d.ts
Labels: src:TypeScript

#761 Add focus() method for focusing DayPicker wrapper
  src/DayPicker.js
  test/daypicker/methods.js
  types/DayPicker.d.ts
Labels: docs: required update, new feature, v:minor

#824 Fix text wrapping on DayPicker-Day
  lib/style.css
Labels: v:patch

#816 When DayPicker input state is controlled, correctly set the input text on 'value' prop updates
  src/DayPickerInput.js
  test/daypickerinput/events.js
Labels: need investigation 🔬, v:minor
