Repository gpbl/react-day-picker, pull requests merged in 2019-08, with the labels that each got.

#904 fix(types): update type export to allow importing DateUtils methods
  types/index.d.ts
Labels: src:TypeScript, v:minor

#881 Fix different time when date is typed in the input field
  src/DayPickerInput.js
  test/daypickerinput/events.js
  test/daypickerinput/methods.js
Labels: src:DayPickerInput, v:patch

#916 Fix typing v7.3.1
  package.json
  types/DayPicker.d.ts
  types/DayPickerInput.d.ts
  types/common.d.ts
  types/index.d.ts
  types/moment.d.ts
  types/props.d.ts
  types/utils.d.ts
  yarn.lock
Labels: help wanted, src:TypeScript
