Repository gpbl/react-day-picker, pull requests merged in 2019-02, with the labels that each got.

#843 Make months and weekdays types slightly less restrictive
  types/props.d.ts
Labels: src:TypeScript, v:patch

#842 Add missing props from weekdayElement and caption Element
  types/props.d.ts
Labels: src:TypeScript, v:patch

#834 Add missing utils export in TS definitions
  types/index.d.ts
Labels: src:TypeScript

#833 Added missing default entries to ClassNames
  types/common.d.ts
Labels: src:TypeScript, v:patch

#831 Adds onDayPickerShow to complement onDayPickerHide
  src/DayPickerInput.js
  test/daypickerinput/events.js
  types/props.d.ts
Labels: docs: required update, src:DayPickerInput, v:minor

#821 Fixed a typo in docs
  docs/src/pages/examples/months-reverse.js
Labels: docs, v:patch

#818 a11y: Set week number tabIndex to -1 if onWeekClick is not defined
  src/Month.js
Labels: a11y, v:minor

#806 Adding TypeScript declaration for moment locale utils
  moment.d.ts
  package.json
  types/moment.d.ts
Labels: src:TypeScript, v:patch

#832 Add style prop to DayPickerInput
  src/DayPickerInput.js
Labels: src:DayPickerInput, v:patch
