Repository gpbl/react-day-picker, pull requests merged in 2020-04, with the labels that each got.

#1004 aria-disabled and aria-selected break when using custom classNames prop
  src/Month.js
Labels: Priority: Medium, Type: Bug, Type: Maintenance

#996 Add style type to DayPickerInputProps (fix #966)
  types/props.d.ts
Labels: Priority: Medium, Type: Bug

#990 Fix input field clear
  src/DayPickerInput.js
  src/Month.js
Labels: Priority: High, Status: In Progress, Type: Bug, Type: Testing

#1012 DayPicker props renderDay and renderWeek are optional
  types/props.d.ts
Labels: Status: Accepted, Type: Bug

#1011 Export MomentLocaleUtils as value
  types/moment.d.ts
Labels: Status: Accepted, Type: Bug

#1020 Add DayPicker dir export
  DayPicker/index.js
  DayPicker/package.json
  package.json
Labels: Priority: Low, Type: Maintenance

#968 Use moment localeData via documented API
  src/addons/MomentLocaleUtils.js
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#1019 Replace rollup with webpack
  .gitignore
  .prettierrc
  .yarn/build-state.yml
  .yarn/install-state.gz
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
  .yarn/releases/yarn-berry.js
  packages/react-day-picker/package.json
  packages/react-day-picker/rollup.config.js
  packages/react-day-picker/tsconfig.dist.json
  packages/react-day-picker/tsconfig.json
  packages/react-day-picker/tsconfig.types.json
  packages/react-day-picker/tslint.json
  packages/react-day-picker/webpack.config.ts
  yarn.lock
Labels: Type: Maintenance

#1024 Rename types file to uppercase because linux imports are case sensitive
  types/Props.d.ts
Labels: Priority: High, Type: Bug

#1026 Update selected multiple example
  docs/src/code-samples/examples/selected-multiple.js
Labels: Type: Documentation
