Repository gpbl/react-day-picker, pull requests merged in 2021-12, with the labels that each got.

#1308 chore: limit exports
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/components/index.ts
  packages/react-day-picker/src/contexts/DayPicker/utils/parseModifierProps.ts
  packages/react-day-picker/src/contexts/Focus/index.ts
  packages/react-day-picker/src/contexts/Navigation/index.ts
  packages/react-day-picker/src/contexts/RootProvider.tsx
  packages/react-day-picker/src/contexts/SelectMultiple/index.ts
  packages/react-day-picker/src/contexts/SelectRange/index.ts
  packages/react-day-picker/src/contexts/SelectSingle/index.ts
  packages/react-day-picker/src/contexts/index.ts
  packages/react-day-picker/src/hooks/index.ts
Labels: Type: Maintenance, Type: Documentation

#1300 feat: add extended keyboard navigation
  packages/react-day-picker/src/components/Day/hooks/useDayFocus.ts
  packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
  test-integration/examples/keyboard.test.tsx
  test/po.ts
Labels: Type: Feature, Priority: Medium, Status: Accepted

#1325 chore: renamed caption elements
  packages/react-day-picker/src/components/Root/Root.tsx
  packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts
  packages/react-day-picker/src/types/Styles.ts
  packages/react-day-picker/style.css
  packages/react-day-picker/style.css.d.ts
Labels: Type: Maintenance

#1328 repo: add no-console eslint rule
  .eslintrc.js
Labels: Type: Developer Experience

#1329 chore: rename style to multiple_months
  packages/react-day-picker/src/components/Root/Root.tsx
  packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts
  packages/react-day-picker/src/types/Styles.ts
Labels: Type: Maintenance

#1319 fix: missing today modifier
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/contexts/DayPicker/DayPickerContext.ts
  packages/react-day-picker/src/contexts/DayPicker/DayPickerProvider.tsx
  packages/react-day-picker/src/contexts/DayPicker/utils/index.ts
  packages/react-day-picker/src/contexts/DayPicker/utils/parseModifierProps.ts
  packages/react-day-picker/src/contexts/Modifiers/ModifiersContext.tsx
  packages/react-day-picker/src/contexts/Modifiers/index.ts
  packages/react-day-picker/src/contexts/Modifiers/useModifiers.ts
  packages/react-day-picker/src/contexts/RootProvider.tsx
  packages/react-day-picker/src/contexts/SelectMultiple/SelectMultipleContext.tsx
  packages/react-day-picker/src/contexts/SelectRange/SelectRangeContext.tsx
  packages/react-day-picker/src/contexts/SelectSingle/SelectSingleContext.tsx
  packages/react-day-picker/src/hooks/useDayModifiers/index.ts
  packages/react-day-picker/src/hooks/useDayModifiers/useDayModifiers.test.ts
  packages/react-day-picker/src/hooks/useDayModifiers/useDayModifiers.ts
  packages/react-day-picker/src/hooks/useDayModifiers/utils/getModifierStatus.ts
  packages/react-day-picker/src/hooks/useDayModifiers/utils/isDateInRange.ts
  packages/react-day-picker/src/hooks/useDayModifiers/utils/isMatch.ts
  packages/react-day-picker/src/hooks/useModifiers/index.ts
  packages/react-day-picker/src/hooks/useModifiers/types/UseModifiers.ts
  packages/react-day-picker/src/hooks/useModifiers/types/index.ts
  packages/react-day-picker/src/hooks/useModifiers/useModifiers.ts
  packages/react-day-picker/src/types/DayPicker.ts
  packages/react-day-picker/src/types/DayPickerCustom.ts
  website/test-integration/examples/modifiers-today.test.tsx
Labels: Type: Bug

#1327 chore: Month component
  packages/react-day-picker/src/components/Month/Month.test.tsx
  packages/react-day-picker/src/components/Month/Month.tsx
  packages/react-day-picker/src/components/Month/index.ts
  packages/react-day-picker/src/components/Root/Root.test.tsx
  packages/react-day-picker/src/components/Root/Root.tsx
Labels: Type: Maintenance

#1333 chore: update test utils docs and API
  packages/react-day-picker/test/render/customRender.tsx
  packages/react-day-picker/test/render/customRenderHook.tsx
Labels: Type: Testing, Type: Developer Experience

#1334 chore: use abbr for weekday names in Head
  packages/react-day-picker/src/components/Head/Head.tsx
  packages/react-day-picker/src/contexts/DayPicker/labels/labelWeekday.ts
Labels: Type: a11y

#1335 feat: caption element to be h2
  packages/react-day-picker/src/components/CaptionLabel/CaptionLabel.tsx
Labels: Type: a11y

#1336 fix: rename caption_first to caption_start
  packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts
  packages/react-day-picker/style.css
  packages/react-day-picker/style.css.d.ts
Labels: Type: Bug, Type: Refactoring

#1337 chore: move Table to grid role
  packages/react-day-picker/src/components/Table/Table.tsx
  packages/react-day-picker/test/po/index.ts
Labels: Type: a11y

#1342 package: move from rollup to tsc
  .github/workflows/react-day-picker.yml
  .github/workflows/website.yml
  packages/react-day-picker/package.json
  packages/react-day-picker/rollup.config.js
  packages/react-day-picker/tsconfig.cjs.json
  packages/react-day-picker/tsconfig.esm.json
  website/docusaurus.typedoc.js
  yarn.lock
Labels: Type: Package

#1343 feat: build a more intelligent target focused day
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/components/Day/hooks/useDayFocus.ts
  packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
  packages/react-day-picker/src/contexts/Focus/getInitialFocusTarget.tsx
  packages/react-day-picker/test/po/po.ts
  website/examples/keyboard.tsx
  website/test-integration/examples/keyboard-focus.test.tsx
Labels: Type: a11y

#1351 feat: support for putting initial focus on the day grid
  packages/react-day-picker/src/components/Day/hooks/useDayFocus.ts
  packages/react-day-picker/src/components/Root/Root.tsx
  packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
  packages/react-day-picker/src/types/DayPicker.ts
  website/test-integration/examples/keyboard-focus.test.tsx
Labels: Type: Feature, Type: a11y

#1355 chore: update keyboard focus integration tests
  packages/react-day-picker/test/po/po.ts
  website/examples/keyboard.tsx
  website/test-integration/examples/keyboard-focus.test.tsx
  website/test-integration/examples/keyboard.test.tsx
Labels: Type: Testing

#1358 feat: use caption labels
  packages/react-day-picker/package.json
  packages/react-day-picker/src/components/Caption/Caption.test.tsx
  packages/react-day-picker/src/components/Caption/Caption.tsx
  packages/react-day-picker/src/components/CaptionLabel/CaptionLabel.tsx
  packages/react-day-picker/src/components/Month/Month.test.tsx
  packages/react-day-picker/src/components/Month/Month.tsx
  packages/react-day-picker/src/components/Table/Table.tsx
  packages/react-day-picker/test/po/po.ts
  website/package.json
  website/test-integration/examples/controlled.test.tsx
  website/test-integration/examples/default-month.test.tsx
  website/test-integration/examples/disabled.test.tsx
  website/test-integration/examples/dropdown.test.tsx
  website/test-integration/examples/keyboard.test.tsx
  website/test-integration/examples/multiple-months-paged.test.tsx
  website/test-integration/examples/multiple-months.test.tsx
  website/test-integration/examples/spanish.test.tsx
  yarn.lock
Labels: Type: a11y

#1360 chore: add tests for the ModifiersContext
  packages/react-day-picker/src/contexts/DayPicker/DayPickerContext.tsx
  packages/react-day-picker/src/contexts/DayPicker/defaultContextValues.ts
  packages/react-day-picker/src/contexts/Modifiers/ModifiersContext.tsx
  packages/react-day-picker/src/contexts/Modifiers/utils/getCustomModifiers.test.ts
  packages/react-day-picker/src/contexts/Modifiers/utils/getCustomModifiers.ts
  packages/react-day-picker/src/contexts/Modifiers/utils/getInternalModifiers.test.ts
  packages/react-day-picker/src/contexts/Modifiers/utils/getInternalModifiers.ts
  packages/react-day-picker/src/contexts/Modifiers/utils/matcherToArray.test.ts
  packages/react-day-picker/src/contexts/Modifiers/utils/matcherToArray.ts
  packages/react-day-picker/src/contexts/SelectMultiple/SelectMultipleContext.tsx
  packages/react-day-picker/src/contexts/SelectRange/SelectRangeContext.tsx
  packages/react-day-picker/src/types/DayPicker.ts
  packages/react-day-picker/src/types/Modifiers.ts
Labels: Type: Testing

#1347 docs: add dialog example
  website/docs/guides/date-picker-dialog.md
  website/docusaurus.sidebars.js
  website/examples/date-picker-dialog.tsx
  website/package.json
  website/src/custom.css
  website/src/theme/CodeBlock/index.tsx
  website/src/theme/CodeBlock/sandbox/styles-dark.css
  website/src/theme/CodeBlock/sandbox/styles.css
  yarn.lock
Labels: Type: Documentation

#1368 chore(website): add dependencies to SandPack via includes
  website/docs/guides/date-picker-dialog.md
  website/package.json
  website/src/theme/CodeBlock/index.tsx
Labels: Type: Documentation

#1370 chore(website): update dialog example
  website/docs/guides/date-picker-dialog.md
  website/examples/date-picker-dialog.tsx
  website/test-integration/examples/date-picker-dialog.test.tsx
Labels: Type: Documentation
