Repository gpbl/react-day-picker, pull requests merged in 2021-11, with the labels that each got.

#1241 docs: fix typo
  packages/react-day-picker/README.md
Labels: Type: Documentation

#1238 Update Navigation.tsx
  packages/react-day-picker/src/components/Navigation/Navigation.tsx
Labels: Type: Bug, Priority: High

#1230 Fix DateUtils.addDayToRange second argument typing
  types/DateUtils.d.ts
Labels: Type: Bug, Status: Review Needed, Priority: Medium, v7 (maintenance)

#1270 (fix) Week numbers may break at end/begin of the years
  packages/react-day-picker/src/components/Table/Table.tsx
  packages/react-day-picker/src/components/Table/utils/getWeeks.test.ts
  packages/react-day-picker/src/components/Table/utils/getWeeks.ts
Labels: Type: Bug, Priority: High

#1275 (fix) useDay `isOutside` is always true
  packages/react-day-picker/src/components/Day/hooks/useDay.test.tsx
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/components/Table/utils/getWeeks.ts
Labels: Type: Bug

#1276 (feat) Allow fully "controlled" range and multiple modes
  packages/react-day-picker/src/DayPicker.tsx
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/contexts/Navigation/useNavigationState.ts
  packages/react-day-picker/src/contexts/SelectMultiple/SelectMultipleProvider.tsx
  packages/react-day-picker/src/contexts/SelectRange/SelectRangeProvider.tsx
  packages/react-day-picker/src/contexts/SelectSingle/SelectSingleProvider.tsx
  packages/react-day-picker/src/hooks/useControllablePropState/index.ts
  packages/react-day-picker/src/hooks/useControllablePropState/useControllablePropState.tsx
  packages/react-day-picker/src/hooks/useInput/types/UseInputDayPickerProps.ts
  packages/react-day-picker/src/hooks/useInput/useInput.ts
  packages/react-day-picker/src/types/DayPickerBase.ts
  packages/react-day-picker/src/types/DayPickerCustom.ts
  packages/react-day-picker/src/types/DayPickerMultiple.ts
  packages/react-day-picker/src/types/DayPickerProps.ts
  packages/react-day-picker/src/types/DayPickerRange.ts
  packages/react-day-picker/src/types/DayPickerSingle.ts
  packages/react-day-picker/src/types/DayPickerUncontrolled.ts
  packages/react-day-picker/src/types/index.ts
  packages/react-day-picker/src/types/isDayPickerCustom.ts
  packages/react-day-picker/src/types/isDayPickerUncontrolled.ts
  website/docs/basics/navigation.mdx
  website/docs/basics/selecting-days.mdx
  website/docs/guides/custom-selections.md
  website/examples/custom-selection-multiple.tsx
  website/examples/custom-selection-single.tsx
  website/examples/navigation-controlled.tsx
  website/examples/selecting-days-multiple-controlled.tsx
  website/examples/selecting-days-range-controlled.tsx
Labels: Status: Blocked, Priority: High, require docs update

#1290 (chore) Refactor DayPickerProps types, remove uncontrolled selections
  packages/react-day-picker/src/DayPicker.tsx
  packages/react-day-picker/src/components/Day/hooks/useDay.tsx
  packages/react-day-picker/src/contexts/SelectMultiple/SelectMultipleProvider.tsx
  packages/react-day-picker/src/contexts/SelectMultiple/SelectMultipleProviderInternal.tsx
  packages/react-day-picker/src/contexts/SelectRange/SelectRangeProvider.tsx
  packages/react-day-picker/src/contexts/SelectRange/SelectRangeProviderInternal.tsx
  packages/react-day-picker/src/contexts/SelectSingle/SelectSingleProvider.tsx
  packages/react-day-picker/src/contexts/SelectSingle/SelectSingleProviderInternal.tsx
  packages/react-day-picker/src/hooks/useModifiers/useModifiers.test.tsx
  packages/react-day-picker/src/test/customRenderHook.tsx
  packages/react-day-picker/src/types/DayPickerBase.ts
  packages/react-day-picker/src/types/DayPickerCustom.ts
  packages/react-day-picker/src/types/DayPickerCustomProps.ts
  packages/react-day-picker/src/types/DayPickerMultipleProps.ts
  packages/react-day-picker/src/types/DayPickerProps.ts
  packages/react-day-picker/src/types/DayPickerRange.ts
  packages/react-day-picker/src/types/DayPickerRangeProps.ts
  packages/react-day-picker/src/types/DayPickerSingle.ts
  packages/react-day-picker/src/types/DayPickerSingleProps.ts
  packages/react-day-picker/src/types/index.ts
  packages/react-day-picker/src/types/isDayPickerCustom.ts
  packages/react-day-picker/src/types/isDayPickerMultiple.tsx
  packages/react-day-picker/src/types/isDayPickerRange.tsx
  packages/react-day-picker/src/types/isDayPickerSingle.ts
  website/docs/basics/navigation.mdx
  website/docs/basics/selecting-days.mdx
  website/docs/guides/custom-selections.md
  website/docs/guides/modifiers.md
  website/examples/custom-selection-single.tsx
  website/examples/custom-selection-useday.tsx
  website/examples/customization-weeknumber.tsx
  website/examples/modifiers-classnames.tsx
  website/examples/modifiers-custom.tsx
  website/examples/modifiers-disabled.tsx
  website/examples/modifiers-hidden.tsx
  website/examples/modifiers-style.tsx
  website/examples/modifiers-today-change.tsx
  website/examples/modifiers-today.tsx
  website/examples/navigation-default-month.tsx
  website/examples/navigation-disabled.tsx
  website/examples/navigation-dropdown.tsx
  website/examples/navigation-from-to-month.tsx
  website/examples/navigation-from-to-year.tsx
  website/examples/selecting-days-multiple-controlled.tsx
  website/examples/selecting-days-multiple-min-max.tsx
  website/examples/selecting-days-multiple.tsx
  website/examples/selecting-days-range-controlled.tsx
  website/examples/selecting-days-range-min-max.tsx
  website/examples/selecting-days-range.tsx
  website/examples/selecting-days-single-min.tsx
  website/examples/selecting-days-single.tsx
  website/examples/styling-css.tsx
  website/examples/styling-inline.tsx
  website/src/components/RenderExample.module.css
  website/src/components/RenderExample.tsx
  website/src/components/index.ts
  website/src/custom.css
  website/src/theme/CodeBlock/index.tsx
  website/src/theme/CodeBlock/styles.module.css
Labels: Type: Maintenance

#1293 (chore) useInput cleanup
  packages/react-day-picker/src/hooks/useInput/index.ts
  packages/react-day-picker/src/hooks/useInput/types/UseInput.ts
  packages/react-day-picker/src/hooks/useInput/types/UseInputDayPickerProps.ts
  packages/react-day-picker/src/hooks/useInput/types/UseInputFieldProps.ts
  packages/react-day-picker/src/hooks/useInput/types/UseInputOptions.ts
  packages/react-day-picker/src/hooks/useInput/types/index.ts
  packages/react-day-picker/src/hooks/useInput/useInput.ts
  website/docs/guides/input-fields.md
  website/examples/input-fields.tsx
Labels: Type: Maintenance
